CREATE TABLE WORSHIP$2020_08_19 AS(
SELECT ATT_MEMBERS.MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_GROUP, MEETING_TIME
FROM ATT_MEMBERS JOIN ATT_ATTENDANCE
ON MEETING_NAME = 'WORSHIP' AND MEETING_DATE = '2020-08-19' AND ATT_MEMBERS.MEMBER_ID = ATT_ATTENDANCE.MEMBER_ID);
