INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0004','HARRY','MERCADO','CORREA','VILLAGE','123123123','MEMBER','GROUP3');
INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0004','PEDRO','SALAZAR','LILI','BARCELONA','1234','MEMBER','GROUP3');
INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0005','MARCO ANTONIO','LUIS','LUIS','MADRID','1234','MEMBER','GROUP1');
INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0004','HOLA','K ASE','KASE','2FEWDF','123','MEMBER','GROUP1');
INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0004','EGERTRE','RTER','ERT','ETRET','324234','MEMBER','GROUP1');
INSERT INTO ATT_MEMBERS(MEMBER_ID, MEMBERNAME, MEMBERMIDDLENAME, MEMBERSURNAME, MEMBER_ADDRESS, MEMBER_TELEPHONE, MEMBER_STATUS, MEMBER_GROUP)
VALUES('0004','HOLA','SOYPRUEBA','TEST','OIOI','1234','OFFICER','GROUP2');
