INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','29/07/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('SCHOOL','07/08/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('SCHOOL BUKOL','07/08/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('SCHOOL 3','07/08/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','18/08/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('TESTING','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('FHFH','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('ERTE','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('RYRTYT','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('BIBLE STUDY','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('TESTING','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('BIBLE STUDY','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('PRAYER MEETING','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('LALA','07/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','09/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('SHALALALA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('LELELEL','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('YYY','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('YY','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('BIBLE STUDY','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('LKL','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('TEST','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('POPO','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('EWR','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('DFD','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('RTR','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('RTRT','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('RT','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('ERER','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('DFDF','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('PRAYER MEETING','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('DEVOTION','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAAA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAAAA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAAAAA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('QQQQ','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AA','10/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','12/09/2019');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('POKLÑKLÑ','2020-01-09');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('TEST','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIPR','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('AAAAA','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('SORSHIP','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('RETE','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('FFS','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('DD','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('FF','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('CVCV','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('LOLO','2020-01-10');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('TEST','2020-03-02');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('HI','2020-03-02');
INSERT INTO ATT_MEETINGS(MEETING_NAME, MEETING_DATE)
VALUES('WORSHIP','2020-03-02');
